**# MATRIX CREATION**

In [ ]:
import numpy as np

WAP to create an autothreshhold algorithm.
1. create a 9x9 matrix within a range of 0-100 integer number.
2. find the avg of each row and save it in a B list (1x9).

Step 2: [B0,B,B2,B3,B4,B5,B6,B7,B8]
3. Now, Compare the values of each row with its respective MEAN. If mean vcalue is greater than the element, then leave the element as it is, else make the element 0. Create a new matric C to hold the updated result.
4. Count the no. of zeros & non zero elements, which should be equal to the no. of elements in a matrix.

In [3]:
# creating a 9x9 matrix
np.random.seed(5)
A = np.random.randint(0,100,size=(9,9))
print("Input Matrix")
print(A.shape[0])
print ("\n",A)

#step 2
B = [] #empty list for storing means

for i in range (0,A.shape[0],1):
    temp = A[i,:].mean()
    B.append(temp) #save the mean on the respective position of the B list
print("\n",B)

#step 3 & 4
C = np.zeros((A.shape[0],A.shape[1]))
ZerosCount = 0
NonZerosCount = 0
for i in range(A.shape[0]):
    for j in range(A.shape[0]):
        if (A[i,j])>B[i]:
            C[i,j] = 0
            ZerosCount=ZerosCount+1
        else:
            C[i,j] = A[i,j]
            NonZerosCount=NonZerosCount+1

print("\nNo. of zeros are: ",ZerosCount)
print("No. of non-zeros are: ",NonZerosCount)

if (NonZerosCount+ZerosCount == A.size):
    print("\nUpdated Matrix is Verified!")
else:
    print("\nUpdated Matrix is not validated!")

print("\nUpdated Matrix")
print(C)

Input Matrix
9

 [[99 78 61 16 73  8 62 27 30]
 [80  7 76 15 53 80 27 44 77]
 [75 65 47 30 84 86 18  9 41]
 [62  1 82 16 78  5 58  0 80]
 [ 4 36 51 27 31  2 68 38 83]
 [19 18  7 30 62 11 67 65 55]
 [ 3 91 78 27 29 33 89 85  7]
 [16 94 14 90 31  9 38 47 16]
 [ 5 34 45 59 24 13 31 32 76]]

 [50.44444444444444, 51.0, 50.55555555555556, 42.44444444444444, 37.77777777777778, 37.111111111111114, 49.111111111111114, 39.44444444444444, 35.44444444444444]

No. of zeros are:  37
No. of non-zeros are:  44

Updated Matrix is Verified!

Updated Matrix
[[ 0.  0.  0. 16.  0.  8.  0. 27. 30.]
 [ 0.  7.  0. 15.  0.  0. 27. 44.  0.]
 [ 0.  0. 47. 30.  0.  0. 18.  9. 41.]
 [ 0.  1.  0. 16.  0.  5.  0.  0.  0.]
 [ 4. 36.  0. 27. 31.  2.  0.  0.  0.]
 [19. 18.  7. 30.  0. 11.  0.  0.  0.]
 [ 3.  0.  0. 27. 29. 33.  0.  0.  7.]
 [16.  0. 14.  0. 31.  9. 38.  0. 16.]
 [ 5. 34.  0.  0. 24. 13. 31. 32.  0.]]


**# SLICING**

In [ ]:
np.random.seed(5)
A = np.random.randint(1,20,size=(4,4))
print("Input Matrix:\n",A)
print("\nSize of Matrix:",A.shape, "\n")

print("------------------------- \n")
print("MANUAL SLICING!!! \n")

A1 = A[:2,:2]
print("A1 matrix is: \n", A1)
A1 = np.zeros((A.shape[0]//2, A.shape[1]//2))
print("Zeros of A1 matrix is: \n", A1, "\n")

A2 = A[:2,2:]
print("A2 matrix is: \n", A2)
A2 = np.zeros((A.shape[0]//2, A.shape[1]//2))
print("Zeros of A2 matrix is: \n", A2, "\n")

A3 = A[2:,:2]
print("A3 matrix is: \n", A3)
A3 = np.zeros((A.shape[0]//2, A.shape[1]//2))
print("Zeros of A3 matrix is: \n", A3, "\n")

A4 = A[2:,2:]
print("A4 matrix is: \n", A4)
A4 = np.zeros((A.shape[0]//2, A.shape[1]//2))
print("Zeros of A4 matrix is: \n", A4, "\n")


# Loop Slicing now!


print("------------------------- \n")
print("LOOP SLICING!!!")

Result = np.zeros((int(A.shape[0]/2), int(A.shape[1]/2)))
rows,cols = A.shape
max_matrix = np.zeros((rows//2,cols//2), dtype=int)

for i in range(0,A.shape[0],2):
    for j in range(0,A.shape[1],2):
        temp = A [i:i+2, j:j+2]
        print()
        print(temp)

        max_value = temp.max()
        print(f"Max Value: {max_value}")

        max_matrix[i//2, j//2] = max_value

print("\n------------------------- ")
print("\nMatrix of max values:\n",max_matrix)

Input Matrix:
 [[ 4 15 16  7]
 [17 10  9  5]
 [ 8 17 17  8]
 [13 16 18  8]]

Size of Matrix: (4, 4) 

------------------------- 

MANUAL SLICING!!! 

A1 matrix is: 
 [[ 4 15]
 [17 10]]
Zeros of A1 matrix is: 
 [[0. 0.]
 [0. 0.]] 

A2 matrix is: 
 [[16  7]
 [ 9  5]]
Zeros of A2 matrix is: 
 [[0. 0.]
 [0. 0.]] 

A3 matrix is: 
 [[ 8 17]
 [13 16]]
Zeros of A3 matrix is: 
 [[0. 0.]
 [0. 0.]] 

A4 matrix is: 
 [[17  8]
 [18  8]]
Zeros of A4 matrix is: 
 [[0. 0.]
 [0. 0.]] 

------------------------- 

LOOP SLICING!!!

[[ 4 15]
 [17 10]]
Max Value: 17

[[16  7]
 [ 9  5]]
Max Value: 16

[[ 8 17]
 [13 16]]
Max Value: 17

[[17  8]
 [18  8]]
Max Value: 18

------------------------- 

Matrix of max values:
 [[17 16]
 [17 18]]
